# ---- Mjolnir Configuration ----
# -------------------------------

material: GOLDEN_AXE
name: "&6Mjölnir"

ench:
  - sharpness:3

lore:
  - "&3The Hammer of Thor"
  - ""
  - "&1Right click to throw."
  - "&1Shift right click to summon lightning."
  - "&1Shift right click while looking up to supercharge."
  - "&1While supercharged, your abilities are enhanced."

unbreakable: true
custom_model_data: 0
require_permissions_to_use: false

cooldown_message: "&6%ability% &cis on cooldown for another &6%time% &cseconds!"
cooldown_in_actionbar: false

abilities:
  throw:
    damage: 10
    ignite: true
    cooldown: 1.5
    show_cooldown: true
  lightning:
    damage: 20
    cooldown: 8
    show_cooldown: true
  supercharge:
    damage: 20
    duration: 14
    cooldown: 120
    show_cooldown: true
    super_abilities:
      throw:
        damage: 20
        ignite: true
        cooldown: 0
        show_cooldown: true
      lightning:
        damage: 20
        explosion_power: 7
        set_fire: true
        break_blocks: true
        cooldown: 2
        show_cooldown: true
